name: itexstore_agent
description: "ITEX Store Agent"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  jitsi_meet_flutter_sdk:
    git: https://github.com/kocallphoneng/jitsi-meet-flutter-sdk.git
  timeago: ^3.6.1
  sembast: ^3.7.1
  stomp_dart_client: ^1.0.3
  path_provider: ^2.1.3
  intl: ^0.19.0
  permission_handler: ^11.2.1
  pointycastle: ^3.8.0
  hive: ^2.2.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI/SegoeUI.ttf
          weight: 400
        - asset: assets/fonts/SegoeUI/SegoeUI_Semi_Bold.ttf
          weight: 500
        - asset: assets/fonts/SegoeUI/SegoeUI_Bold.ttf
          weight: 700
